export const verifiedPoolMap = {
    GitcoinGrantsMatchingPool: {siteUrl: 'https://gitcoin.co/about'},
    UnchainFund: {siteUrl:'https://unchain.fund/'},
    CoinCenter: {siteUrl: 'https://www.coincenter.org/'},
    AidforUkraineCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
    AnimalsCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
    CryptoGrowthCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
    EducationCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
    GunSafetyCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
    'Housing&HungerCauseFund': {siteUrl: 'https://www.cryptoforcharity.io/'},
    'Justice&EqualityCauseFund': {siteUrl: 'https://www.cryptoforcharity.io/'},
    'LGBTQIA2S+CauseFund': {siteUrl: 'https://www.cryptoforcharity.io/'},
    'Military&VeteransCauseFund': {siteUrl: 'https://www.cryptoforcharity.io/'},
    ReproductiveRightsCauseFund: {siteUrl: 'https://www.cryptoforcharity.io/'},
}